name: miniplan
description: "MiniPlan – Günlük Plan + AI Motive Geri Bildirim"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  flutter_local_notifications: ^16.3.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  provider: ^6.1.1
  uuid: ^4.2.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 